export const PROJECTS_WITH_SCAFFOLDING_URL = "project?scaffolding=true"
export const BASE_URL = "http://10.212.138.205:8080/stillastracking/v1/api/"
export const SCAFFOLDING_URL = "unit"
export const STORAGE_URL = "storage"
export const USER_URL = "user"
export const PROJECTS_URL = "project"
export const PROJECTS_URL_WITH_SCAFFOLDING = "project?scaffolding=true"

export const PROJECTS_URL_WITH_ID = "project?id="
export const WITH_SCAFFOLDING_URL = "&scaffolding=true"
export const MAP_STYLE_V11 = "mapbox://styles/mapbox/streets-v11"
export const TRANSFER_SCAFFOLDING = "project/scaffolding"
