version: "3.5"

services:
  broker:
    image: eclipse-mosquitto:2.0
    ports:
      - ${MQTT_PORT}:1883
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mqtt/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
    restart: always

  web:
    container_name: go
    build: ./
    ports:
      - "80:8080"
    restart: always


